#!/usr/bin/env bash
# This script displays "bad luck" on the 4th iteration, "good luck" on the 8th, and "Best School" otherwise

count=1
while [ "$count" -le 10 ]
do
  if [ "$count" -eq 4 ]; then
    echo -e "bad luck"
  elif [ "$count" -eq 8 ]; then
    echo -e "good luck"
  else
    echo -e "Best School"
  fi

  count=$((count + 1))
done
