#!/usr/bin/env bash
# shellcheck disable=SC2009

# Find all PIDs of the 4-to_infinity_and_beyond process and display them
ps -eo pid,cmd | grep 4-to_infinity_and_beyond | grep -v grep | awk {print } | while read pid; do
    echo "Stopping process $pid"
    # Stop the process by sending SIGTERM
    echo "$pid" > /proc/$pid/fd/1 2>/proc/$pid/fd/2
done
