#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely
# Displays "I am invincible!!!" when receiving a SIGTERM signal

# Catch the SIGTERM signal
trap echo I am invinciblegit push! SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
