#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely and shows "I am invincible!!!" when receiving SIGTERM

# Handle SIGTERM
trap echo I am invinciblegit push! SIGTERM

# Infinite loop printing the message every 2 seconds
while true; do
    echo "To infinity and beyond"
    sleep 2
done
